ALTER TABLE lojistas 
ADD COLUMN IF NOT EXISTS cor_principal VARCHAR DEFAULT '#f97316',
ADD COLUMN IF NOT EXISTS cor_secundaria VARCHAR DEFAULT '#111827',
ADD COLUMN IF NOT EXISTS cor_fundo_cards VARCHAR DEFAULT '#1a1a2e',
ADD COLUMN IF NOT EXISTS cor_texto_normal VARCHAR DEFAULT '#ffffff',
ADD COLUMN IF NOT EXISTS cor_texto_secundaria VARCHAR DEFAULT '#9ca3af',
ADD COLUMN IF NOT EXISTS logo_url TEXT,
ADD COLUMN IF NOT EXISTS capa_url TEXT;
